### ISSUE TITLE
1.9.0 CI failure

### ISSUE THREAD

**Issue by gavvvr** [thomis/eventhub-processor2#2]
Before using 1.9.0 I decided to check why [CI fails](https://travis-ci.org/github/thomis/eventhub-processor2/jobs/760591841#L676)

```
  1) EventHub::ActorListener succeeds to publish message
     Failure/Error: expect { @listener.publish(message: EventHub::Message.new.to_json) }.not_to raise_error
       expected no Exception, got #<Celluloid::DeadActorError: attempted to call a dead actor: publish> with backtrace:
         # ./vendor/bundle/ruby/2.6.0/gems/celluloid-0.18.0/lib/celluloid/internals/responses.rb:30:in `value'
         # ./vendor/bundle/ruby/2.6.0/gems/celluloid-0.18.0/lib/celluloid/call/sync.rb:52:in `value'
         # ./vendor/bundle/ruby/2.6.0/gems/celluloid-0.18.0/lib/celluloid/proxy/sync.rb:20:in `method_missing'
         # ./spec/eventhub/listener_spec.rb:12:in `block (3 levels) in <top (required)>'
         # ./spec/eventhub/listener_spec.rb:12:in `block (2 levels) in <top (required)>'
     # ./spec/eventhub/listener_spec.rb:12:in `block (2 levels) in <top (required)>'
```

The reason RabitMQ drops connection is that 'processor2' queue which test processor tries to listen to does not exist initially on a fresh RabbitMQ instance.
Previously tests did not fail, because [the first test](https://github.com/thomis/eventhub-processor2/commit/fcfa5ff9367d090da5a74adcc5fc206cd4a430df#diff-40ad2b9c500e1ebe4bd11b6a0890382d8eb306a83480bd595caa3ea6e625e3b4R6) in listener_spec.rb created the queue.

Why it fails now? Because each test is [not wrapped](https://github.com/thomis/eventhub-processor2/commit/fcfa5ff9367d090da5a74adcc5fc206cd4a430df#diff-40ad2b9c500e1ebe4bd11b6a0890382d8eb306a83480bd595caa3ea6e625e3b4L4) with Celluloid.boot/shutdown anymore and everything happens too fast: connection for the 2nd test gets also rejected, because there is still no missing queue. I do not know what should be a proper solution here. Maybe declaring 'processor2' in 'definitions.json'. But I will leave minimal steps to easily reproduce the issue.

How to reproduce
---

- git checkout v1.9.0
- you will always need a fresh instance of RabbitMQ, so use the following sequence of commands: `docker-compose stop ; docker rm eventhub.rabbitmq ; docker-compose up -d`
- edit `listener_spec.rb`: remove all tests but first two
- `bundle exec rspec spec/eventhub/listener_spec.rb` and you will see an error from CI. Besides checking test logs you can also check: `docker logs eventhub.rabbitmq -f`
- now to reproduce the problem again, get a new instance of RabbitMQ and run the test

Note: If you add `sleep(0.5)` at the end of 1st test, there is no problem, because it is enough time for RabbitMQ to create missing queue. 

Hope my findings will help to solve the issue. Currently there is a dependency between the first test ('gives a valid actor') and subsequent ones. Ideally they should be independent.

**Comment by thomis** [comment]
Hi Kirill

Thanks a lot for brining this up and describing it in such a detail. It was very helpful to reproduce the issue. I was trying with all sorts of changes (w/wo sleep, w/wo definition of the processor2 queue/exchange) but there was not really a different behaviour. Then I realised that it takes time for the rabbitmq container to start up. By waiting about 10s and only then running the test it works without sleep and predefinition of the queue/exchange. So, I added this as a precondition for the tests: Support.ensure_rabbitmq_is_available

`module Support
  def self.ensure_rabbitmq_is_available
    Bunny.new(vhost: "event_hub", user: "guest", password: "guest").start
  rescue
    puts "Waiting for rabbitmq to be available..."
    sleep 1
    retry
  end
end`

With this it runs stable again. Please try and let me know. There is now Version 3.10.0 release with more log noise removed ;-)

Best

Thomi
